import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.css';

import products from './../data/data.json';
import ProductCard from '../components/ProductCard';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next product catalogue - Leo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Products</h1>
        <div className="card__wrapper">
          {products.map((product, i) => (
            <Link key={i} href={`products/${product.id}`}>
              <a>
                <ProductCard product={JSON.stringify(product)} />
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
}
